import {
  Book,
  Waveform,
  MusicNotesSimple,
  AirplaneTilt,
  PawPrint,
  Barbell,
  Heart,
  Scroll,
  BabyCarriage,
  Brain,
  Bread,
  Briefcase,
  Camera,
  Campfire,
  ChefHat,
  City,
  Cloud,
  Club,
  Code,
  Cpu,
  Cube,
  Eyeglasses,
  FilmSlate,
  GlobeHemisphereWest,
  Grains,
  HouseLine,
  Layout,
  Lego,
  Martini,
  Money,
  Network,
  PaintBrush,
  PenNibStraight,
  Planet,
  PottedPlant,
  Sailboat,
  Television,
  TShirt,
  Users,
  QuestionMark,
  LightbulbFilament,
  Hammer,
  ChatCircle,
  Person,
  GraduationCap,
  Flask,
  Blueprint,
  Swatches,
  Tag,
  ListNumbers,
} from "@phosphor-icons/react";

export const icons = [
  { name: "tag", icon: Tag },
  { name: "book", icon: Book },
  { name: "waveform", icon: Waveform },
  { name: "musicNotesSimple", icon: MusicNotesSimple },
  { name: "airplaneTilt", icon: AirplaneTilt },
  { name: "pawPrint", icon: PawPrint },
  { name: "barbell", icon: Barbell },
  { name: "heart", icon: Heart },
  { name: "paintBrush", icon: PaintBrush },
  { name: "money", icon: Money },
  { name: "code", icon: Code },
  { name: "cloud", icon: Cloud },
  { name: "houseLine", icon: HouseLine },
  { name: "lightbulbFilament", icon: LightbulbFilament },
  { name: "hammer", icon: Hammer },
  { name: "person", icon: Person },
  { name: "users", icon: Users },
  { name: "babyCarriage", icon: BabyCarriage },
  { name: "lego", icon: Lego },
  { name: "club", icon: Club },
  { name: "campfire", icon: Campfire },
  { name: "planet", icon: Planet },
  { name: "network", icon: Network },
  { name: "filmSlate", icon: FilmSlate },
  { name: "martini", icon: Martini },
  { name: "chefHat", icon: ChefHat },
  { name: "sailboat", icon: Sailboat },
  { name: "bread", icon: Bread },
  { name: "grains", icon: Grains },
  { name: "pottedPlant", icon: PottedPlant },
  { name: "penNibStraight", icon: PenNibStraight },
  { name: "eyeglasses", icon: Eyeglasses },
  { name: "tShirt", icon: TShirt },
  { name: "briefcase", icon: Briefcase },
  { name: "graduationCap", icon: GraduationCap },
  { name: "flask", icon: Flask },
  { name: "blueprint", icon: Blueprint },
  { name: "swatches", icon: Swatches },
  { name: "globeHemisphereWest", icon: GlobeHemisphereWest },
  { name: "camera", icon: Camera },
  { name: "television", icon: Television },
  { name: "cpu", icon: Cpu },
  { name: "city", icon: City },
  { name: "brain", icon: Brain },
  { name: "chatCircle", icon: ChatCircle },
  { name: "layout", icon: Layout },
  { name: "scroll", icon: Scroll },
  { name: "listNumbers", icon: ListNumbers },
  { name: "cube", icon: Cube },
  { name: "questionMark", icon: QuestionMark },
];
