import {
  BookOpen,
  MusicNotesSimple,
  AirplaneTilt,
  PawPrint,
  Barbell,
  Heart,
  Scroll,
  BabyCarriage,
  Brain,
  Bread,
  Briefcase,
  Camera,
  Campfire,
  ChefHat,
  City,
  Cloud,
  Club,
  Code,
  Cpu,
  Cube,
  Eyeglasses,
  FilmSlate,
  GlobeHemisphereWest,
  HouseLine,
  Lego,
  Martini,
  Money,
  MaskHappy,
  PaintBrush,
  PenNib,
  Planet,
  PottedPlant,
  Sailboat,
  TShirt,
  UsersThree,
  QuestionMark,
  LightbulbFilament,
  Hammer,
  ChatCircle,
  Person,
  GraduationCap,
  Flask,
  Blueprint,
  Swatches,
  Tag,
  ListNumbers,
  NoteBlank,
  Database,
  Car,
  CardsThree,
  Devices,
  Folder,
  MathOperations,
  ShieldCheckered,
  BookmarkSimple,
  Signpost,
  Bug,
  Binoculars,
  Tray,
} from "@phosphor-icons/react";

export const icons = [
  { name: "tag", icon: Tag },
  { name: "bookOpen", icon: BookOpen },
  { name: "musicNotesSimple", icon: MusicNotesSimple },
  { name: "airplaneTilt", icon: AirplaneTilt },
  { name: "pawPrint", icon: PawPrint },
  { name: "barbell", icon: Barbell },
  { name: "heart", icon: Heart },
  { name: "paintBrush", icon: PaintBrush },
  { name: "money", icon: Money },
  { name: "cloud", icon: Cloud },
  { name: "hammer", icon: Hammer },
  { name: "lightbulbFilament", icon: LightbulbFilament },
  { name: "houseLine", icon: HouseLine },
  { name: "car", icon: Car },
  { name: "person", icon: Person },
  { name: "usersThree", icon: UsersThree },
  { name: "babyCarriage", icon: BabyCarriage },
  { name: "lego", icon: Lego },
  { name: "club", icon: Club },
  { name: "campfire", icon: Campfire },
  { name: "shieldCheckered", icon: ShieldCheckered },
  { name: "planet", icon: Planet },
  { name: "filmSlate", icon: FilmSlate },
  { name: "maskHappy", icon: MaskHappy },
  { name: "martini", icon: Martini },
  { name: "chefHat", icon: ChefHat },
  { name: "sailboat", icon: Sailboat },
  { name: "bread", icon: Bread },
  { name: "pottedPlant", icon: PottedPlant },
  { name: "bug", icon: Bug },
  { name: "PenNib", icon: PenNib },
  { name: "eyeglasses", icon: Eyeglasses },
  { name: "tShirt", icon: TShirt },
  { name: "briefcase", icon: Briefcase },
  { name: "graduationCap", icon: GraduationCap },
  { name: "flask", icon: Flask },
  { name: "blueprint", icon: Blueprint },
  { name: "swatches", icon: Swatches },
  { name: "city", icon: City },
  { name: "globeHemisphereWest", icon: GlobeHemisphereWest },
  { name: "binoculars", icon: Binoculars },
  { name: "signpost", icon: Signpost },
  { name: "camera", icon: Camera },
  { name: "brain", icon: Brain },
  { name: "chatCircle", icon: ChatCircle },
  { name: "scroll", icon: Scroll },
  { name: "bookmarkSimple", icon: BookmarkSimple },
  { name: "mathOperations", icon: MathOperations },
  { name: "code", icon: Code },
  { name: "cpu", icon: Cpu },
  { name: "database", icon: Database },
  { name: "devices", icon: Devices },
  { name: "listNumbers", icon: ListNumbers },
  { name: "noteBlank", icon: NoteBlank },
  { name: "folder", icon: Folder },
  { name: "tray", icon: Tray },
  { name: "cardsThree", icon: CardsThree },
  { name: "cube", icon: Cube },
  { name: "questionMark", icon: QuestionMark },
];
