/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as CreateJournalImport } from './routes/create-journal'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutJournalIdUpdatesImport } from './routes/_layout.$journalId.updates'
import { Route as LayoutJournalIdTasksImport } from './routes/_layout.$journalId.tasks'
import { Route as LayoutJournalIdNotesImport } from './routes/_layout.$journalId.notes'
import { Route as LayoutJournalIdBookmarkedImport } from './routes/_layout.$journalId.bookmarked'
import { Route as LayoutJournalIdTagsTagIdImport } from './routes/_layout.$journalId.tags.$tagId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const CreateJournalRoute = CreateJournalImport.update({
  id: '/create-journal',
  path: '/create-journal',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutJournalIdUpdatesRoute = LayoutJournalIdUpdatesImport.update({
  id: '/$journalId/updates',
  path: '/$journalId/updates',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalIdTasksRoute = LayoutJournalIdTasksImport.update({
  id: '/$journalId/tasks',
  path: '/$journalId/tasks',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalIdNotesRoute = LayoutJournalIdNotesImport.update({
  id: '/$journalId/notes',
  path: '/$journalId/notes',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalIdBookmarkedRoute = LayoutJournalIdBookmarkedImport.update({
  id: '/$journalId/bookmarked',
  path: '/$journalId/bookmarked',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalIdTagsTagIdRoute = LayoutJournalIdTagsTagIdImport.update({
  id: '/$journalId/tags/$tagId',
  path: '/$journalId/tags/$tagId',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/create-journal': {
      id: '/create-journal'
      path: '/create-journal'
      fullPath: '/create-journal'
      preLoaderRoute: typeof CreateJournalImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/$journalId/bookmarked': {
      id: '/_layout/$journalId/bookmarked'
      path: '/$journalId/bookmarked'
      fullPath: '/$journalId/bookmarked'
      preLoaderRoute: typeof LayoutJournalIdBookmarkedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$journalId/notes': {
      id: '/_layout/$journalId/notes'
      path: '/$journalId/notes'
      fullPath: '/$journalId/notes'
      preLoaderRoute: typeof LayoutJournalIdNotesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$journalId/tasks': {
      id: '/_layout/$journalId/tasks'
      path: '/$journalId/tasks'
      fullPath: '/$journalId/tasks'
      preLoaderRoute: typeof LayoutJournalIdTasksImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$journalId/updates': {
      id: '/_layout/$journalId/updates'
      path: '/$journalId/updates'
      fullPath: '/$journalId/updates'
      preLoaderRoute: typeof LayoutJournalIdUpdatesImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/$journalId/tags/$tagId': {
      id: '/_layout/$journalId/tags/$tagId'
      path: '/$journalId/tags/$tagId'
      fullPath: '/$journalId/tags/$tagId'
      preLoaderRoute: typeof LayoutJournalIdTagsTagIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutJournalIdBookmarkedRoute: typeof LayoutJournalIdBookmarkedRoute
  LayoutJournalIdNotesRoute: typeof LayoutJournalIdNotesRoute
  LayoutJournalIdTasksRoute: typeof LayoutJournalIdTasksRoute
  LayoutJournalIdUpdatesRoute: typeof LayoutJournalIdUpdatesRoute
  LayoutJournalIdTagsTagIdRoute: typeof LayoutJournalIdTagsTagIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutJournalIdBookmarkedRoute: LayoutJournalIdBookmarkedRoute,
  LayoutJournalIdNotesRoute: LayoutJournalIdNotesRoute,
  LayoutJournalIdTasksRoute: LayoutJournalIdTasksRoute,
  LayoutJournalIdUpdatesRoute: LayoutJournalIdUpdatesRoute,
  LayoutJournalIdTagsTagIdRoute: LayoutJournalIdTagsTagIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/create-journal': typeof CreateJournalRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/$journalId/bookmarked': typeof LayoutJournalIdBookmarkedRoute
  '/_layout/$journalId/notes': typeof LayoutJournalIdNotesRoute
  '/_layout/$journalId/tasks': typeof LayoutJournalIdTasksRoute
  '/_layout/$journalId/updates': typeof LayoutJournalIdUpdatesRoute
  '/_layout/$journalId/tags/$tagId': typeof LayoutJournalIdTagsTagIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/$journalId/bookmarked'
    | '/$journalId/notes'
    | '/$journalId/tasks'
    | '/$journalId/updates'
    | '/$journalId/tags/$tagId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/$journalId/bookmarked'
    | '/$journalId/notes'
    | '/$journalId/tasks'
    | '/$journalId/updates'
    | '/$journalId/tags/$tagId'
  id:
    | '__root__'
    | '/_layout'
    | '/create-journal'
    | '/login'
    | '/signup'
    | '/_layout/$journalId/bookmarked'
    | '/_layout/$journalId/notes'
    | '/_layout/$journalId/tasks'
    | '/_layout/$journalId/updates'
    | '/_layout/$journalId/tags/$tagId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CreateJournalRoute: typeof CreateJournalRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CreateJournalRoute: CreateJournalRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/create-journal",
        "/login",
        "/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/$journalId/bookmarked",
        "/_layout/$journalId/notes",
        "/_layout/$journalId/tasks",
        "/_layout/$journalId/updates",
        "/_layout/$journalId/tags/$tagId"
      ]
    },
    "/create-journal": {
      "filePath": "create-journal.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/$journalId/bookmarked": {
      "filePath": "_layout.$journalId.bookmarked.tsx",
      "parent": "/_layout"
    },
    "/_layout/$journalId/notes": {
      "filePath": "_layout.$journalId.notes.tsx",
      "parent": "/_layout"
    },
    "/_layout/$journalId/tasks": {
      "filePath": "_layout.$journalId.tasks.tsx",
      "parent": "/_layout"
    },
    "/_layout/$journalId/updates": {
      "filePath": "_layout.$journalId.updates.tsx",
      "parent": "/_layout"
    },
    "/_layout/$journalId/tags/$tagId": {
      "filePath": "_layout.$journalId.tags.$tagId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
