/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutFlaggedImport } from './routes/_layout.flagged'
import { Route as LayoutJournalsJournalIdImport } from './routes/_layout.journals.$journalId'
import { Route as LayoutDayDateStringImport } from './routes/_layout.day.$dateString'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutFlaggedRoute = LayoutFlaggedImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutJournalsJournalIdRoute = LayoutJournalsJournalIdImport.update({
  id: '/journals/$journalId',
  path: '/journals/$journalId',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutDayDateStringRoute = LayoutDayDateStringImport.update({
  id: '/day/$dateString',
  path: '/day/$dateString',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/flagged': {
      id: '/_layout/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof LayoutFlaggedImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/day/$dateString': {
      id: '/_layout/day/$dateString'
      path: '/day/$dateString'
      fullPath: '/day/$dateString'
      preLoaderRoute: typeof LayoutDayDateStringImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/journals/$journalId': {
      id: '/_layout/journals/$journalId'
      path: '/journals/$journalId'
      fullPath: '/journals/$journalId'
      preLoaderRoute: typeof LayoutJournalsJournalIdImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutFlaggedRoute: typeof LayoutFlaggedRoute
  LayoutDayDateStringRoute: typeof LayoutDayDateStringRoute
  LayoutJournalsJournalIdRoute: typeof LayoutJournalsJournalIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutFlaggedRoute: LayoutFlaggedRoute,
  LayoutDayDateStringRoute: LayoutDayDateStringRoute,
  LayoutJournalsJournalIdRoute: LayoutJournalsJournalIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flagged': typeof LayoutFlaggedRoute
  '/day/$dateString': typeof LayoutDayDateStringRoute
  '/journals/$journalId': typeof LayoutJournalsJournalIdRoute
}

export interface FileRoutesByTo {
  '': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/flagged': typeof LayoutFlaggedRoute
  '/day/$dateString': typeof LayoutDayDateStringRoute
  '/journals/$journalId': typeof LayoutJournalsJournalIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/flagged': typeof LayoutFlaggedRoute
  '/_layout/day/$dateString': typeof LayoutDayDateStringRoute
  '/_layout/journals/$journalId': typeof LayoutJournalsJournalIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/flagged'
    | '/day/$dateString'
    | '/journals/$journalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/signup'
    | '/flagged'
    | '/day/$dateString'
    | '/journals/$journalId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/flagged'
    | '/_layout/day/$dateString'
    | '/_layout/journals/$journalId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login",
        "/signup"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/flagged",
        "/_layout/day/$dateString",
        "/_layout/journals/$journalId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_layout/flagged": {
      "filePath": "_layout.flagged.tsx",
      "parent": "/_layout"
    },
    "/_layout/day/$dateString": {
      "filePath": "_layout.day.$dateString.tsx",
      "parent": "/_layout"
    },
    "/_layout/journals/$journalId": {
      "filePath": "_layout.journals.$journalId.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
